# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
zh:
  languageCode: zh-Hans
  contentDir: content/zh
  title: Academic-DavidZ
  params:
    description: 张家豪的个人学术主页
  menu:
    main:
      - name: 主页
        url: "#about"
        weight: 10
      - name: 文章
        url: "#featured"
        weight: 20
      - name: 项目
        url: "#projects"
        weight: 30
      - name: 经历
        url: "#experience"
        weight: 40
      - name: 获奖
        url: "#accomplishments"
        weight: 50
      - name: 简历
        url: "https://cv.davidz.cn/"
        weight: 60
